services:
  db:
    image: bitnami/postgresql:latest
    container_name: widget-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=upload
    volumes:
      - "./docker:/docker-entrypoint-initdb.d"
    networks:
      - widget

  app:
    build: .
    depends_on:
      - db
    container_name: widget-server
    restart: unless-stopped
    ports:
      - 3000:3333
    environment:
      - PORT=$PORT
      - NODE_ENV=$NODE_ENV
      - DATABASE_URL=$DATABASE_URL
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUDFLARE_BUCKET=$CLOUDFLARE_BUCKET
      - CLOUDFLARE_PUBLIC_URL=$CLOUDFLARE_PUBLIC_URL
    networks:
      - widget

networks:
  widget:
    driver: bridge
